# Generated by Django 5.1.1 on 2024-10-01 19:09

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=' ', max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mat', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, upload_to=app.models.imgFile)),
                ('description', models.CharField(max_length=600)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='app.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(verbose_name='chapitre n/')),
                ('video', models.FileField(blank=True, null=True, upload_to=app.models.VideoFile, verbose_name='video')),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to=app.models.PresentationFile, verbose_name='powerpoint')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=app.models.PdfFile, verbose_name='cours en pdf')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='app.matiere')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
