# Generated by Django 5.1.1 on 2024-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='quizz',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers le quizz'),
        ),
    ]
