# Generated by Django 5.1.1 on 2024-10-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cours_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='devoir',
            field=models.FileField(blank=True, null=True, upload_to='travaux/', verbose_name='Travaux'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='quizz',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers le quiz'),
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exercices/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_attribue', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='app.cours')),
            ],
        ),
    ]
