# Generated by Django 5.1.1 on 2024-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cours_devoir_devoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
