# Generated by Django 5.1.1 on 2024-10-12 10:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_historiqueconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='img',
            field=models.ImageField(blank=True, upload_to=app.models.imgFile),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
