# Generated by Django 5.1.1 on 2024-09-21 10:43

import django.db.models.deletion
import utilisateurs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biographie', models.CharField(blank=True, max_length=500)),
                ('photo', models.ImageField(upload_to=utilisateurs.models.Photo_order)),
                ('type_profile', models.CharField(choices=[('student', 'student'), ('prof', 'prof'), ('admin', 'admin')], default='student', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
